//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: MixFaceWXWidgets.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "MixFaceWXWidgets.h"


// Declare the bitmap loading function
extern void wxC26FAInitBitmapResources();

static bool bBitmapLoaded = false;


mainForm::mainForm(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxFrame(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC26FAInitBitmapResources();
        bBitmapLoaded = true;
    }
    this->SetBackgroundColour(wxColour(wxT("rgb(96,96,96)")));
    wxFont thisFont(14, wxFONTFAMILY_SWISS, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_BOLD, false, wxT("Arial"));
    this->SetFont(thisFont);
    
    wxBoxSizer* mainSizer = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(mainSizer);
    
    topPanel = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,32)), wxTAB_TRAVERSAL|wxBORDER_STATIC);
    wxFont topPanelFont(8, wxFONTFAMILY_SWISS, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_BOLD, false, wxT("Arial"));
    topPanel->SetFont(topPanelFont);
    
    mainSizer->Add(topPanel, 0, wxALL|wxEXPAND, WXC_FROM_DIP(0));
    
    wxBoxSizer* topPanelSizer = new wxBoxSizer(wxHORIZONTAL);
    topPanel->SetSizer(topPanelSizer);
    
    topPanelSizer->Add(0, 0, 1, wxALL, WXC_FROM_DIP(5));
    
    settingsButton = new wxButton(topPanel, wxID_ANY, _("Settings"), wxDefaultPosition, wxDLG_UNIT(topPanel, wxSize(64,28)), wxBORDER_STATIC);
    settingsButton->SetBackgroundColour(wxColour(wxT("rgb(96,96,96)")));
    settingsButton->SetForegroundColour(wxColour(wxT("rgb(255,255,255)")));
    
    topPanelSizer->Add(settingsButton, 0, wxLEFT|wxTOP|wxBOTTOM, WXC_FROM_DIP(4));
    settingsButton->SetMinSize(wxSize(64,28));
    
    topPanelBtnSizer = new wxStdDialogButtonSizer();
    
    topPanelSizer->Add(topPanelBtnSizer, 0, wxALL, WXC_FROM_DIP(4));
    topPanel->SetMinSize(wxSize(-1,32));
    
    wxBoxSizer* botSizer = new wxBoxSizer(wxHORIZONTAL);
    
    mainSizer->Add(botSizer, 1, wxALL|wxEXPAND, WXC_FROM_DIP(0));
    
    scrollPanel = new wxScrolledWindow(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxBORDER_STATIC|wxHSCROLL|wxVSCROLL);
    scrollPanel->SetScrollRate(5, 5);
    
    botSizer->Add(scrollPanel, 1, wxALL|wxEXPAND, WXC_FROM_DIP(0));
    
    wxBoxSizer* scrollPanelSizer = new wxBoxSizer(wxHORIZONTAL);
    scrollPanel->SetSizer(scrollPanelSizer);
    
    mainPanel = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(128,-1)), wxTAB_TRAVERSAL|wxBORDER_STATIC);
    
    botSizer->Add(mainPanel, 0, wxALL|wxEXPAND, WXC_FROM_DIP(0));
    
    wxBoxSizer* mainPanelSizer = new wxBoxSizer(wxVERTICAL);
    mainPanel->SetSizer(mainPanelSizer);
    mainPanel->SetMinSize(wxSize(128,-1));
    
    rightPanel = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(64,-1)), wxTAB_TRAVERSAL|wxBORDER_STATIC);
    
    botSizer->Add(rightPanel, 0, wxALL|wxEXPAND, WXC_FROM_DIP(0));
    
    wxBoxSizer* rightPanelSizer = new wxBoxSizer(wxVERTICAL);
    rightPanel->SetSizer(rightPanelSizer);
    
    rightPanelSizer->Add(0, 0, 1, wxALL, WXC_FROM_DIP(5));
    
    busButton = new wxButton(rightPanel, wxID_ANY, _("LR"), wxDefaultPosition, wxDLG_UNIT(rightPanel, wxSize(50,40)), 0);
    busButton->SetBackgroundColour(wxColour(wxT("rgb(96,96,96)")));
    busButton->SetForegroundColour(wxColour(wxT("rgb(255,255,255)")));
    
    rightPanelSizer->Add(busButton, 0, wxALL|wxALIGN_CENTER, WXC_FROM_DIP(1));
    busButton->SetMinSize(wxSize(50,40));
    
    assignButton = new wxButton(rightPanel, wxID_ANY, _("A\nB\nC\nD\nE\nF"), wxDefaultPosition, wxDLG_UNIT(rightPanel, wxSize(50,150)), 0);
    assignButton->SetBackgroundColour(wxColour(wxT("rgb(96,96,96)")));
    assignButton->SetForegroundColour(wxColour(wxT("rgb(255,255,255)")));
    
    rightPanelSizer->Add(assignButton, 0, wxALL|wxALIGN_CENTER, WXC_FROM_DIP(0));
    assignButton->SetMinSize(wxSize(50,150));
    
    rightPanelSizer->Add(0, 0, 1, wxALL, WXC_FROM_DIP(5));
    rightPanel->SetMinSize(wxSize(64,-1));
    
    SetBackgroundColour(wxColour(wxT("rgb(96,96,96)")));
    SetName(wxT("mainForm"));
    SetMinClientSize(wxSize(1280,720));
    SetSize(wxDLG_UNIT(this, wxSize(-1,-1)));
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
    if(GetParent()) {
        CentreOnParent(wxBOTH);
    } else {
        CentreOnScreen(wxBOTH);
    }
#if wxVERSION_NUMBER >= 2900
    if(!wxPersistenceManager::Get().Find(this)) {
        wxPersistenceManager::Get().RegisterAndRestore(this);
    } else {
        wxPersistenceManager::Get().Restore(this);
    }
#endif
}

mainForm::~mainForm()
{
}
