//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: MixFaceWXWidgets.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _MIXFACE_MIXFACEWXWIDGETS_MIXFACEWXWIDGETS_BASE_CLASSES_H
#define _MIXFACE_MIXFACEWXWIDGETS_MIXFACEWXWIDGETS_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/panel.h>
#include <wx/button.h>
#include <wx/scrolwin.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif


class mainForm : public wxFrame
{
protected:
    wxPanel* topPanel;
    wxButton* settingsButton;
    wxStdDialogButtonSizer* topPanelBtnSizer;
    wxScrolledWindow* scrollPanel;
    wxPanel* mainPanel;
    wxPanel* rightPanel;
    wxButton* busButton;
    wxButton* assignButton;

protected:

public:
    wxButton* GetSettingsButton() { return settingsButton; }
    wxPanel* GetTopPanel() { return topPanel; }
    wxScrolledWindow* GetScrollPanel() { return scrollPanel; }
    wxPanel* GetMainPanel() { return mainPanel; }
    wxButton* GetBusButton() { return busButton; }
    wxButton* GetAssignButton() { return assignButton; }
    wxPanel* GetRightPanel() { return rightPanel; }
    mainForm(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("MixFace"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(-1,-1), long style = wxDEFAULT_FRAME_STYLE);
    virtual ~mainForm();
};

#endif
