//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: MixFaceFader.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _MIXFACE_MIXFACEWXWIDGETS_MIXFACEFADER_BASE_CLASSES_H
#define _MIXFACE_MIXFACEWXWIDGETS_MIXFACEFADER_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/panel.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/button.h>
#include <wx/slider.h>
#include "dbMeter.h"
#include <wx/bmpbuttn.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif


class MixFaceFaderBase : public wxPanel
{
protected:
    wxButton* m_button772;
    wxButton* m_button793;
    wxButton* m_button814;
    wxButton* m_button835;
    wxSlider* m_slider916;
    singleDBMeterPanel* m_panel102212;
    singleDBMeterPanel* m_panel10213;
    wxSlider* m_slider75114;
    wxButton* m_button8516;
    wxBitmapButton* m_bmpButton8917;

protected:

public:
    wxButton* GetButton772() { return m_button772; }
    wxButton* GetButton793() { return m_button793; }
    wxButton* GetButton814() { return m_button814; }
    wxButton* GetButton835() { return m_button835; }
    wxSlider* GetSlider916() { return m_slider916; }
    singleDBMeterPanel* GetPanel102212() { return m_panel102212; }
    singleDBMeterPanel* GetPanel10213() { return m_panel10213; }
    wxSlider* GetSlider75114() { return m_slider75114; }
    wxButton* GetButton8516() { return m_button8516; }
    wxBitmapButton* GetBmpButton8917() { return m_bmpButton8917; }
    MixFaceFaderBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(128,600), long style = wxTAB_TRAVERSAL);
    virtual ~MixFaceFaderBase();
};

#endif
